import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { orderAPI } from "../services/api";

const money = (value) => `₹${Number(value || 0).toFixed(2)}`;
export default function OrderHistory() {
  const [orders, setOrders] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { orderAPI.getOrders().then((r) => setOrders(r.data.orders)).catch(() => toast.error("Could not load your orders.")).finally(() => setLoading(false)); }, []);
  return <div className="min-h-screen bg-slate-50 flex flex-col"><Navbar /><main className="flex-1 max-w-5xl mx-auto w-full px-4 py-8"><p className="text-xs font-semibold text-blue-600 uppercase tracking-widest">Purchases</p><h1 className="text-3xl font-bold text-slate-900 mb-7">Order history</h1>{loading ? <div className="grid place-items-center py-20"><div className="w-9 h-9 border-4 border-blue-600 border-t-transparent rounded-full animate-spin" /></div> : orders.length === 0 ? <div className="bg-white border border-slate-200 rounded-2xl p-12 text-center"><p className="font-semibold text-slate-800">No orders yet</p><Link to="/" className="inline-block mt-3 text-blue-600">Start shopping →</Link></div> : <div className="space-y-4">{orders.map((order) => <article key={order.id} className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm"><header className="px-5 py-4 bg-slate-50 border-b border-slate-100 flex flex-wrap gap-3 justify-between"><div><p className="font-semibold text-slate-900">Order #{order.id}</p><p className="text-sm text-slate-500">{new Date(order.created_at).toLocaleDateString("en-IN", { dateStyle: "medium" })}</p></div><div className="text-right"><span className="inline-flex bg-emerald-100 text-emerald-700 px-2.5 py-1 rounded-full text-xs font-bold uppercase">{order.status}</span><p className="font-bold mt-1">{money(order.total)}</p></div></header><div className="p-5 space-y-3">{order.items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0">{item.image_url && <img src={item.image_url} alt="" className="w-11 h-11 rounded-lg object-cover bg-slate-100" />}<div className="min-w-0"><p className="font-medium text-slate-800 truncate">{item.name}</p><p className="text-xs text-slate-500">{item.quantity} × {money(item.unit_price)}</p></div></div><span className="font-medium text-slate-700">{money(item.subtotal)}</span></div>)}</div></article>)}</div>}</main><Footer /></div>;
}
